databases:
  # Banco de dados PostgreSQL
  - name: postgres_db
    plan: free
    databaseName: app_db
    user: user
    ipAllowList: []  # Permite conexões de qualquer IP

services:
  # Backend FastAPI
  - type: web
    name: fastapi_backend
    env: docker
    plan: free
    docker:
      dockerfile: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_db
          property: connectionString
    # Adicione outras variáveis de ambiente se necessário

  # Frontend React
  - type: web
    name: react_frontend
    env: docker
    plan: free
    docker:
      dockerfile: ./frontend/Dockerfile